name       : python-qtpy
version    : 1.9.0
release    : 7
source     :
    - https://github.com/spyder-ide/qtpy/archive/v1.9.0.tar.gz : a6783acab8f7f7b04026c7da19c65bf904d69629d06d951cb7b9344468270c5b
license    : MIT
component  : programming.python
summary    : Provides an uniform layer to support PyQt5, PySide2, PyQt4 and PySide with a single codebase
description: |
    QtPy is a small abstraction layer that lets you write applications using a single API call to either PyQt or PySide. It provides support for PyQt5, PyQt4, PySide2 and PySide using the Qt5 layout (where the QtGui module has been split into QtGui and QtWidgets). Basically, you write your code as if you were using PySide2 but import Qt modules from qtpy instead of PySide2 (or PyQt5).
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python3-qt5
build      : |
    %python3_setup
install    : |
    %python3_install
